project:
  type: website   
  output-dir: docs  
 
website:
  title: ""  # Titel der Website
  sidebar:
    collapse-level: 1
    style: docked  # Fest angeheftete Sidebar
    pinned: false
    contents:
      - text: "<strong>Post Navigator</strong>"
      - section: "MacroShift"   
        contents:
          - text: "MacroShift - Underlying Theory"
            href: MacroShift_Theory.qmd
      - section: "Blog Posts"   
        contents:
          - text: "Markov-Switching Models"
            href: Markov_Switching_Models.qmd     
  #    - section: "Blog Posts"
  #      contents: 
  #        - text: "Regularisation Methods"   
  #          href: index.qmd
  #    - section: "Replication Projects"
  #      contents: 
  #        - text: "History's Masters 2025" 
  #          href: index.qmd
  #        - text: "Card and Krueger 1994"
  #          href: index.qmd
  navbar:
    logo: "images/Logo2.png"  # Logo in der Navbar
    background: primary
    search: true
    left:
      - text: "Start"
        href: index.qmd              
      - text: "About Me" 
        href: AboutMe.qmd
     - text: "GitHub"
        href: https://github.com/jmuelleo
       
format:
  html:
    theme: cerulean
    css: styles.css  # Benutzerdefinierte CSS-Datei
    toc: true  # Inhaltsverzeichnis aktivieren 