project:
  type: website   
  output-dir: docs  
 
website:
  title: ""  # Titel der Website
  sidebar:
    collapse-level: 1
    style: docked  # Fest angeheftete Sidebar
    pinned: false
    contents:
      - text: "<strong>Post Navigator</strong>"
      - section: "MacroShift"   
        contents:
          - text: "MacroShift - Anticipating Recessions. Allocating with Precision."
            href: 
      - section: "Blog Posts"
        contents:
          - text: "Regularisation Methods"   
            href: 
      - section: "Replication Projects"
        contents:
          - text: "History's Masters 2025" 
            href: 
          - text: "Card and Krueger 1994"
            href: 
  navbar:
    logo: "images/Logo2.png"  # Logo in der Navbar
    background: primary
    search: true
    left:
      - text: "Start"
        href: about.qmd              
      - text: "About Me" 
        href: AboutMe.qmd
      - text: "Recent Posts"
        href: Post_Navigator.qmd   
       
format:
  html:
    theme: cerulean
    css: styles.css  # Benutzerdefinierte CSS-Datei
    toc: true  # Inhaltsverzeichnis aktivieren 