project:
  type: website   
  output-dir: docs  
 
website:
  title: ""  # Titel der Website
  sidebar:
    collapse-level: 1
    style: docked  # Fest angeheftete Sidebar
    pinned: false
    contents:
      - text: "<strong>Post Navigator</strong>"
    # - section: "MacroShift"   
    #    contents:
    #      - text: "MacroShift - Underlying Theory"
    #        href: MacroShift_Theory.qmd
      - section: "Blog Posts"   
        contents:
          - text: "Markov-Switching Models"
            href: Markov_Switching_Models.qmd     
    #  - section: "Selected Fiverr Projects"
    #    contents: 
    #      - text: "GARCH vs MSARCH"   
    #        href: index.qmd
            
  #    - section: "Replication Projects"
  #      contents: 
  #        - text: "History's Masters 2025" 
  #          href: index.qmd
  #        - text: "Card and Krueger 1994"
  #          href: index.qmd
      - section: "My time at Oxford"
        contents: 
          - text: "My time at Oxford" 
            href: My_Oxford_Time.qmd
#         - text: "Card and Krueger 1994"
#           href: index.qmd
  navbar:
   # logo: "images/Logo2.png"  # Logo in der Navbar
    background: primary
    search: true
    left:
      - text: "Start"
        href: index.qmd              
      - text: "About Me" 
        href: AboutMe.qmd
  #   - text: "Services (Fiverr)" 
  #      href: Fiverr.qmd  
      - text: "My Time in Oxford" 
        href: My_Oxford_Time.qmd
    right:
      - icon: github
        href: "https://github.com/jmuelleo"
        target: _blank
        aria-label: "GitHub"
      - icon: linkedin
        href: "https://www.linkedin.com/in/julian-m%C3%BCller-6b9974250/"
        target: _blank
        aria-label: "LinkedIn"  
      - icon: instagram
        href: "https://www.instagram.com/julianmueller6416/"
        target: _blank
        aria-label: "Instagram"  
      - icon: youtube
        href: "https://www.youtube.com/channel/UC-iICKVCNn7iEQicgRDTudw"
        target: _blank
        aria-label: "YouTube"          
        
        
       
format:
  html:
    theme: cerulean
    css: styles.css  # Benutzerdefinierte CSS-Datei
    toc: true  # Inhaltsverzeichnis aktivieren 