---
title: "(Nearly) Weekly Oxford Updates"
editor: visual
---

# Disclaimer
The following texts are my personal thoughts, unfiltered and unchanged. I the text is intended to be honest, but also humorous, sarcastic, over the top and funny. I do not intend to offend or wrong anyone, it's simply my attempt of writing a lighthearted chronicle of my time at Oxford, thus everything should'nt be taken too seriously and with a grain of salt.




# Michaelmas Term





## 20.09.2025
Today is the 20th September 2025, it's 9pm and this is the first time that I start writing these Update texts. In pretty much exactly one week I will be in Oxford, at least that's the plan. I hope that writing these texts will serve as a creative hobby to pursue as a break from statistics, I see the videos I will create in a similar fashion, I want to have something that allows me to take a break form math and statistics and to do something different, that isn't a complete waste of time (like watching Love Island - Yes, I know that I'm going to be murdered in England for this statement).

I am very excited to have this chance, quite frankly I never imagined myself to be this fortunate. Back in highschool I often had Cs or sometimes even Ds in math, so yeah I really didn't think I would end up doing a Statistics Masters at the University of Oxford, lol.
(Yes, I am going to write "lol" and other cringe stuff, like writing "cringe", fuck it we ball is the motto! -No really, I want to give an unfiltered perspective, my real thoughts, not some instagram, picture perfect twisted version of my experience. Whenever I see people post about Oxford it's always extremely glamorous, everything is perfect, they always suceed and nothing ever goes wrong, maybe Oxford is this magic place where everything just works out, but who knows, as someone who's parents did not go to any Elite University or something like that, I would have loved to have some unfiltered insights, which I found very difficult to acquire -> So here I am, ready to use this excuse to never refine or read my own texts and just write my thoughts down, for everyone to mock).

I think I went on a bit of a tangent, however the main point is that I am very excited to go to Oxford and that I am really lucky, I really am. Also I want to give some unfiltered insights, so that it becomes less intimidating to apply and clearer what to expect.

I mean, you can read about who I am in the "About Me" section, but if you are too lazy to switch to that page, just keep reading. I am 21 years old right now, I turned 21 nearly one month ago (21.08.2004 is my birthday), I finished my Bachelor's Degree in Economics at the University of Mannheim (Germany's best University for Economics, as every Mannheim Graduate needs to point out every time we tell someone where we graduated from - No, there is no argument that Bonn or Munich are better, that's a blatant lie spread by graduates from Bonn or Munich, every intelligent person knows Mannheim is number one!) with a perfect GPA of 1.0 (1.0 is the best, 4.0 is the worst in Germany), with that I finished in the top 0.3%. Sounds good doesn't it? I guess it's not too bad, but still, it misses some points. I studied economics, even so I specialized in Statistics and Econometrics I did not pursue a degree in Mathematics or Statistics, which is definitely something that worries me. The MSc. in Statistical Science at the University of Oxford is a pure Statistics degree, many who will pursue that degree will probably have a pure math or statistics background, at the very least physics or computer science or engineering I guess, I don't know how well I will hold up as an econ guy. Furthermore, I still sometimes question whether I am good enough at math. I mean I received very positive feedback from my professors during my time at Mannheim, but being bad at math throughout your whole school time, like since you were 10 till you were 17, that definitely does not improve your confidence regarding math. But on the other hand, if I can do it that means that everyone who sucked at math back in school can learn it, sounds like a hopeful message to me.

So yeah, welcome to my journey through Oxford, we will see whether I will make it and hopefully I can give some valuable insights along the way (and a text that is interesting and not entirely serious)!
















